---
extends: conditional
message: "'%s' has no definition"
level: error
first: \b([A-Z]{3,5})\b
second: (?:\b[A-Z][a-z]+[']? )+\(([A-Z]{3,5})\)
exceptions:
    - ABC
    - ADD
    - ADHD
    - AIDS
    - APA
    - API
    - BBN
    - CBS
    - CIA
    - CMB
    - CNN
    - CSI
    - CSS
    - CST
    - CWT
    - DWT
    - ESPN
    - EST
    - FAQ
    - FBI
    - FIXME
    - FWHM
    - GOV
    - GNU
    - HIV
    - HR
    - HTML
    - HTTP
    - HTTPS
    - JSON
    - LAN
    - MIT
    - MLA
    - MLB
    - MTV
    - NAACP
    - NASA
    - NATO
    - NBA
    - NBC
    - NCAA
    - NCAAB
    - NCAAF
    - NFL
    - NHL
    - NOTE
    - PDF
    - PGA
    - PPV
    - PST
    - SGML
    - SMICA
    - SNR
    - SSHT
    - SSN
    - SVD
    - TNT
    - TODO
    - UCL
    - URL
    - USA
    - USSR
    - XML
    - XXX
