---
extends: conditional
message: "'%s' has no definition"
level: error
first: \b([A-Z]{3,5})\b
second: (?:\b[A-Z][a-z]+[']? )+\(([A-Z]{3,5})\)
exceptions:
    - CNN
    - FWHM
    - PDF
    - SSHT
    - SVD
    - UCL
