repos:
    # - repo: https://gitlab.salort.eu/jsalort/latexhook
    #   rev: 7879fc02
    #   hooks:
    #       - id: latexindent
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-yaml
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace
