---
repos:
  - repo: https://github.com/paddyroddy/.github
    rev: v0.101.0
    hooks:
      - id: general-hooks
  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.23.4
    hooks:
      - id: latexindent
