[files]
extend-exclude = [
    "*.bib",
    ".github/styles",
]

[type.cls]
extend-glob = [
    "*.cls",
]
extend-ignore-re = [
    "\\\\(begin|end)\\{\\w+\\}",
]

[type.tex]
extend-words.Gorry = "Gorry"
extend-words.SME = "SME"
extend-words.Unser = "Unser"
