---
extends: existence
message: In general, don't use an ellipsis.
link: https://docs.microsoft.com/en-us/style-guide/punctuation/ellipses
nonword: true
level: error
action:
  name: remove
tokens:
  - \.\.\.
