---
extends: existence
message: "avoid using '%s'"
scope: text
level: error
ignorecase: true
tokens:
  - attendees
  - draftees
  - enrollees
  - escapees
  - indictees
  - retirees
  - standees
  - '[\w]+-style'
