---
extends: existence
message: "'%s' - Do not be hectoring or arrogant"
description: "Those who disagree with you are not necessarily '%s.'"
scope: text
level: error
ignorecase: true
tokens:
  - stupid
  - idiotic
  - imbecile
  - ignorant
  - insane
  - absurd
  - ridiculous
  - lunatic
  - asinine
