---
extends: existence
message: Go easy on the oughts and shoulds
description:
  The aim is not just to tell readers what you think, but to persuade them.
scope: text
level: error
ignorecase: true
tokens:
  - ought
  - should
