---
extends: substitution
message: Prefer '%s' over of '%s'
level: error
scope: text
ignorecase: true
swap:
  actionable: practical
  # initially: at first
  lifestyle: way of life
  # media: press
  phone: telephone
  photo: photograph
  simplistic: naive
