---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/add-to-project@abe020ffefc8a3519f965671214a96da0c806b2d # v0
        with:
          project-token: ${{ secrets.PROJECT_PAT }}
