---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/add-to-project@1255ca6dc3bf6f7291aba6c1e8aa7225892d69d9 # v0
        with:
          project-token: ${{ secrets.PROJECT_PAT }}
