name: 'Delete old artifacts'
on:
  schedule:
    - cron: '5 * * * *' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: o # Setting this to 0 will delete all artifacts
