name: deploy

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  chktex:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/chktex@0860bb5de5029a6ef6adbd1da9655eafc9c8231f # v0

  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/vale@0860bb5de5029a6ef6adbd1da9655eafc9c8231f # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vale-flags: --glob='!{config/,figures/*/example_,thesis}*'

  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/compile@0860bb5de5029a6ef6adbd1da9655eafc9c8231f # v0

      - name: Upload artefacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: artefacts
          path: |-
            *.bib
            *.bcf
            *.pdf
          if-no-files-found: error

  check-citations-referenced:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: artefacts

      - name: Fix regex for checkcites
        uses: xu-cheng/texlive-action@d9f893f837a29f066e3c70080540976b47263721 # v2
        id: references
        with:
          scheme: full
          run: |-
            sed -i 's#\sglob="false"##' thesis.bcf
            echo uncited=$(checkcites -b biber thesis -u | grep -c "=>") >> \
            $GITHUB_OUTPUT

      - name: Check all references cited
        if: ${{ steps.references.outputs.uncited > 0 }}
        uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7
        with:
          script: core.setFailed('Not all references cited')

  upload-to-dropbox:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: artefacts

      - uses: paddyroddy/.github/actions/dropbox@0860bb5de5029a6ef6adbd1da9655eafc9c8231f # v0
        with:
          configfile-version: ${{ secrets.CONFIGFILE_VERSION }}
          files-to-upload: $(find . -maxdepth 1 -name '*.pdf' -print)
          oauth-app-key: ${{ secrets.OAUTH_APP_KEY }}
          oauth-app-secret: ${{ secrets.OAUTH_APP_SECRET }}
          oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}
