name: deploy

on: [push, pull_request]

jobs:
    chktex:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Run chktex
              uses: xu-cheng/texlive-action/full@v1
              with:
                  run: |
                      chktex main.tex | tee /dev/stderr | (! grep -q ^); \

    vale:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Run Vale
              uses: errata-ai/vale-action@v1.3.0
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                  files: |
                      '["main.tex", "content"]'

    build-pdfs:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Build PDF
              uses: xu-cheng/texlive-action/full@v1
              with:
                  run: |
                      latexmk -quiet -pdf main.tex

            - name: Upload PDFs
              uses: actions/upload-artifact@v2
              with:
                  name: pdfs
                  path: |
                      *.pdf
                  if-no-files-found: error

    upload-to-dropbox:
        runs-on: ubuntu-latest
        needs: build-pdfs
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Download PDFs
              uses: actions/download-artifact@v2
              with:
                  name: pdfs

            - name: Set up Dropbox
              run: |
                  echo "CONFIGFILE_VERSION=$CONFIGFILE_VERSION" > ~/.dropbox_uploader
                  echo "OAUTH_APP_KEY=$OAUTH_APP_KEY" >> ~/.dropbox_uploader
                  echo "OAUTH_APP_SECRET=$OAUTH_APP_SECRET" >> ~/.dropbox_uploader
                  echo "OAUTH_REFRESH_TOKEN=$OAUTH_REFRESH_TOKEN" >> ~/.dropbox_uploader
              env:
                  CONFIGFILE_VERSION: ${{secrets.CONFIGFILE_VERSION}}
                  OAUTH_APP_KEY: ${{secrets.OAUTH_APP_KEY}}
                  OAUTH_APP_SECRET: ${{secrets.OAUTH_APP_SECRET}}
                  OAUTH_REFRESH_TOKEN: ${{secrets.OAUTH_REFRESH_TOKEN}}

            - name: Upload PDFs
              run: |
                  ./dropbox_uploader.sh upload main.pdf thesis.pdf
