name: deploy

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}

jobs:
  chktex:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/chktex@v0.14.0

  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/vale@v0.14.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vale-flags: --glob='!{config/,figures/*/example_,thesis}*'

  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/compile@v0.14.0

      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: artefacts
          path: |-
            *.bib
            *.bcf
            *.pdf
          if-no-files-found: error

  check-citations-referenced:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
          name: artefacts

      - name: Fix regex for checkcites
        uses: xu-cheng/texlive-action@v2
        id: references
        with:
          scheme: full
          run: |-
            sed -i 's#\sglob="false"##' thesis.bcf
            echo ::set-output name=uncited::\
            $(checkcites -b biber thesis -u | grep -c "=>")

      - name: Check all references cited
        if: ${{ steps.references.outputs.uncited > 0 }}
        uses: actions/github-script@v6
        with:
          script: core.setFailed('Not all references cited')

  upload-to-dropbox:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
          name: artefacts

      - uses: paddyroddy/.github/actions/dropbox@v0.14.0
        with:
          configfile-version: ${{ secrets.CONFIGFILE_VERSION }}
          files-to-upload: $(find . -maxdepth 1 -name '*.pdf' -print)
          oauth-app-key: ${{ secrets.OAUTH_APP_KEY }}
          oauth-app-secret: ${{ secrets.OAUTH_APP_SECRET }}
          oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}
