name: deploy

on: [push, pull_request]

jobs:
    chktex:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v3

            - name: Run chktex
              uses: xu-cheng/texlive-action/full@v1
              with:
                  run: |
                      chktex thesis.tex | tee /dev/stderr | (! grep -q ^)

    vale:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v3

            - name: Run Vale
              uses: errata-ai/vale-action@v1.5.0
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                  files: '[
                      "thesis.tex",
                      "content",
                      "figures",
                      "tables"
                      ]'

    compile-latex:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v3

            - name: Build PDF
              uses: xu-cheng/texlive-action/full@v1
              with:
                  run: |
                      latexmk -quiet

            - name: Upload artifaxts
              uses: actions/upload-artifact@v3
              with:
                  name: artifacts
                  path: |
                      *.bib
                      *.bcf
                      *.pdf
                  if-no-files-found: error

    check-citations-referenced:
        runs-on: ubuntu-latest
        needs: compile-latex
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                  name: artifacts

            - name: Fix regex for checkcites
              uses: xu-cheng/texlive-action/full@v1
              id: references
              with:
                  run: |
                      echo ::set-output name=uncited::\
                        $(checkcites -b biber thesis -u | grep -c "=>")

            - name: Check all references cited
              if: ${{ steps.references.outputs.uncited > 0 }}
              uses: actions/github-script@v6
              with:
                  script: |
                      core.setFailed('Not all references cited')

    upload-to-dropbox:
        runs-on: ubuntu-latest
        needs: compile-latex
        steps:
            - name: checkout source
              uses: actions/checkout@v3

            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                  name: artifacts

            - name: Set up Dropbox
              run: |
                  echo "CONFIGFILE_VERSION=$CONFIGFILE_VERSION" > ~/.dropbox_uploader
                  echo "OAUTH_APP_KEY=$OAUTH_APP_KEY" >> ~/.dropbox_uploader
                  echo "OAUTH_APP_SECRET=$OAUTH_APP_SECRET" >> ~/.dropbox_uploader
                  echo "OAUTH_REFRESH_TOKEN=$OAUTH_REFRESH_TOKEN" >> ~/.dropbox_uploader
              env:
                  CONFIGFILE_VERSION: ${{secrets.CONFIGFILE_VERSION}}
                  OAUTH_APP_KEY: ${{secrets.OAUTH_APP_KEY}}
                  OAUTH_APP_SECRET: ${{secrets.OAUTH_APP_SECRET}}
                  OAUTH_REFRESH_TOKEN: ${{secrets.OAUTH_REFRESH_TOKEN}}

            - name: Upload PDF
              run: |
                  ./dropbox_uploader.sh upload thesis.pdf patrick_roddy_thesis.pdf
