---
name: deploy

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  chktex:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/chktex@512a88ef0d35d185588d460030660a184fc2db36 # v0

  vale:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/vale@512a88ef0d35d185588d460030660a184fc2db36 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vale-flags: --glob='!{config/,figures/*/example_,thesis}*'

  compile-latex:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/compile@512a88ef0d35d185588d460030660a184fc2db36 # v0

      - name: Upload artefacts
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: artefacts
          path: |-
            *.bib
            *.bcf
            *.pdf
          if-no-files-found: error

  check-citations-referenced:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4
        with:
          name: artefacts

      - name: Fix regex for checkcites
        # yamllint disable-line rule:line-length
        uses: xu-cheng/texlive-action@d9f893f837a29f066e3c70080540976b47263721 # v2
        id: references
        with:
          scheme: full
          run: |-
            sed -i 's#\sglob="false"##' thesis.bcf
            echo uncited=$(checkcites -b biber thesis -u | grep -c "=>") >> \
            $GITHUB_OUTPUT

      - name: Check all references cited
        if: ${{ steps.references.outputs.uncited > 0 }}
        # yamllint disable-line rule:line-length
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: core.setFailed('Not all references cited')

  upload-to-dropbox:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4
        with:
          name: artefacts

      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/dropbox@512a88ef0d35d185588d460030660a184fc2db36 # v0
        with:
          configfile-version: ${{ secrets.CONFIGFILE_VERSION }}
          files-to-upload: $(find . -maxdepth 1 -name '*.pdf' -print)
          oauth-app-key: ${{ secrets.OAUTH_APP_KEY }}
          oauth-app-secret: ${{ secrets.OAUTH_APP_SECRET }}
          oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}
