---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@d84abe24680d395c2898a89ae7dd26233de0d4cb # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
