---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@2a7ba19ffbeb4ef996c2adb4f060d498981fb4f0 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
