---
name: Linting

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@b45ffef611d12e0263916cf6f650a9b2cc13aa4f # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
