---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@8182fab2382dfe610271fbb172cc53cbb549431f # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
