name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@909a876d9f25e81524e29bf6463c117d6826855b # v0.20.0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
