---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@d84abe24680d395c2898a89ae7dd26233de0d4cb # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
